config/routes.rb
Rails.application.routes.draw do
  resources :pics
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  get 'signup', to: "users#new"
  post 'signedup', to: "users#create"
  root  to: 'users#index'


  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  get 'logout', to: 'sessions#destroy'

  get 'cars', to: 'cars#index'
  resources :users, only: [:edit, :update,:show]
  resources :cars, only: [:show, :index, :new, :create, :edit, :update]
  resources :orders, only: [:new, :create]
  
  get 'ordered', to: 'cars#display_ordered'
  get 'checkout',to: 'cars#add_to_order'

  get 'search', to: 'cars#search'
  get 'comment',to: 'cars#comment'
  patch 'add_comment',to: 'cars#add_comment'

  
  
end

app/models/user.rb
class User < ApplicationRecord
    has_many :cars, dependent: :delete_all
    has_one :order, dependent: :destroy

    before_save { self.email = email.downcase }


    validates :name, presence: true,
                        length: { minimum:3, maximum: 25 }
    VALID_EMIAL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i

    validates :email, presence: true,
                        uniqueness: { case_sensitive: false },
                        length: { maximum: 105 },
                        format: {with: VALID_EMIAL_REGEX }

PASSWORD_FORMAT = /\A
                  (?=.{8,})          # Must contain 8 or more characters
                  (?=.*\d)           # Must contain a digit
                  (?=.*[a-z])        # Must contain a lower case character
                  (?=.*[A-Z])        # Must contain an upper case character
                  (?=.*[[:^alnum:]]) # Must contain a symbol
                  /x

    validates :password_digest, 
                  presence: true, 
                  format: { with: PASSWORD_FORMAT } 

    validates :address, presence: true



    NUMBER_REGEX = /\d[0-9]\)*\z/


    validates :phone_number, presence: true,
                        length: { minimum:10, maximum:10},
                        format: {with: NUMBER_REGEX }


    
    has_secure_password
                        


end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :no_need_to_login, only: [:index,:new]
    
    def create
         @user=User.new(params.permit(:name, :email,  :address , :phone_number, :user_type, :password))  #add validation
         if @user.save 
            session[:user_id]=@user.id        
            redirect_to login_path, notice: "Successfully Created Account "
         else
            flash.now[:alert]="Please fill in the details...."
            render :new, status: 302
         end

    end

    def index
        if session[:user_id]
            @user=User.find(session[:user_id])
        end
    end
    

    def new
        @user = User.new
    end


    def edit
        if current_user.blank?
            flash[:alert]="you cannot edit please login"
            redirect_to login_path
        elsif current_user.id==params[:id].to_i
            @user=User.find(params[:id])
        else
            flash[:alert]="You can edit only your account"
            redirect_to cars_path
        end
    end

    def update
        @user=User.find(params[:id])
        if @user.update(user_params)
            flash[:notice]="Your account details was successfully updated"
            redirect_to cars_path
        else
            render 'edit', status: 302
        end


    end

    private
    def user_params
        params.require(:user).permit(:name, :email,  :address , :phone_number, :user_type, :password)
                                 
    end

end

app/views/users/edit.html.erb
<style>
.alert{
  padding:20px;
  margin-bottom:20px;
  border: 1px solid black
}

/* BASIC */

html {
  background-color: black;
}

body {
  font-family: "Poppins", sans-serif;
  height: 100vh;
}

a {
  color: #92badd;
  display:inline-block;
  text-decoration: none;
  font-weight: 400;
}

h2 {
  text-align: center;
  font-size: 16px;
  font-weight: 600;
  text-transform: uppercase;
  display:inline-block;
  margin: 40px 8px 10px 8px; 
  color: #cccccc;
}



/* STRUCTURE */

.wrapper {
  display: flex;
  align-items: center;
  flex-direction: column; 
  justify-content: center;
  width: 100%;
  min-height: 100%;
  padding: 20px;
}

#formContent {
  -webkit-border-radius: 10px 10px 10px 10px;
  border-radius: 10px 10px 10px 10px;
  background: #fff;
  padding: 30px;
  width: 90%;
  max-width: 450px;
  position: relative;
  padding: 0px;
  -webkit-box-shadow: 0 30px 60px 0 rgba(0,0,0,0.3);
  box-shadow: 0 30px 60px 0 rgba(0,0,0,0.3);
  text-align: center;
}

#formFooter {
  background-color: #f6f6f6;
  border-top: 1px solid #dce8f1;
  padding: 25px;
  text-align: center;
  -webkit-border-radius: 0 0 10px 10px;
  border-radius: 0 0 10px 10px;
}



/* TABS */

h2.inactive {
  color: #cccccc;
}

h2.active {
  color: #0d0d0d;
  border-bottom: 2px solid #5fbae9;
}



/* FORM TYPOGRAPHY*/

input[type=button], input[type=submit], input[type=reset]  {
  background-color: #56baed;
  border: none;
  color: white;
  padding: 15px 80px;
  text-align: center;
  text-decoration: none;
  display: inline-block;
  text-transform: uppercase;
  font-size: 13px;
  -webkit-box-shadow: 0 10px 30px 0 rgba(95,186,233,0.4);
  box-shadow: 0 10px 30px 0 rgba(95,186,233,0.4);
  -webkit-border-radius: 5px 5px 5px 5px;
  border-radius: 5px 5px 5px 5px;
  margin: 5px 20px 40px 20px;
  -webkit-transition: all 0.3s ease-in-out;
  -moz-transition: all 0.3s ease-in-out;
  -ms-transition: all 0.3s ease-in-out;
  -o-transition: all 0.3s ease-in-out;
  transition: all 0.3s ease-in-out;
}

input[type=button]:hover, input[type=submit]:hover, input[type=reset]:hover  {
  background-color: #39ace7;
}

input[type=button]:active, input[type=submit]:active, input[type=reset]:active  {
  -moz-transform: scale(0.95);
  -webkit-transform: scale(0.95);
  -o-transform: scale(0.95);
  -ms-transform: scale(0.95);
  transform: scale(0.95);
}
textarea {
  background-color: #f6f6f6;
  border: none;
  color: #0d0d0d;
  padding: 15px 32px;
  text-align: center;
  text-decoration: none;
  display: inline-block;
  font-size: 16px;
  margin: 5px;
  width: 85%;
  border: 2px solid #f6f6f6;
  -webkit-transition: all 0.5s ease-in-out;
  -moz-transition: all 0.5s ease-in-out;
  -ms-transition: all 0.5s ease-in-out;
  -o-transition: all 0.5s ease-in-out;
  transition: all 0.5s ease-in-out;
  -webkit-border-radius: 5px 5px 5px 5px;
  border-radius: 5px 5px 5px 5px;
}

input[type=text] {
  background-color: #f6f6f6;
  border: none;
  color: #0d0d0d;
  padding: 15px 32px;
  text-align: center;
  text-decoration: none;
  display: inline-block;
  font-size: 16px;
  margin: 5px;
  width: 85%;
  border: 2px solid #f6f6f6;
  -webkit-transition: all 0.5s ease-in-out;
  -moz-transition: all 0.5s ease-in-out;
  -ms-transition: all 0.5s ease-in-out;
  -o-transition: all 0.5s ease-in-out;
  transition: all 0.5s ease-in-out;
  -webkit-border-radius: 5px 5px 5px 5px;
  border-radius: 5px 5px 5px 5px;
}

input[type=email] {
  background-color: #f6f6f6;
  border: none;
  color: #0d0d0d;
  padding: 15px 32px;
  text-align: center;
  text-decoration: none;
  display: inline-block;
  font-size: 16px;
  margin: 5px;
  width: 85%;
  border: 2px solid #f6f6f6;
  -webkit-transition: all 0.5s ease-in-out;
  -moz-transition: all 0.5s ease-in-out;
  -ms-transition: all 0.5s ease-in-out;
  -o-transition: all 0.5s ease-in-out;
  transition: all 0.5s ease-in-out;
  -webkit-border-radius: 5px 5px 5px 5px;
  border-radius: 5px 5px 5px 5px;
}
input[type=password] {
  background-color: #f6f6f6;
  border: none;
  color: #0d0d0d;
  padding: 15px 32px;
  text-align: center;
  text-decoration: none;
  display: inline-block;
  font-size: 16px;
  margin: 5px;
  width: 85%;
  border: 2px solid #f6f6f6;
  -webkit-transition: all 0.5s ease-in-out;
  -moz-transition: all 0.5s ease-in-out;
  -ms-transition: all 0.5s ease-in-out;
  -o-transition: all 0.5s ease-in-out;
  transition: all 0.5s ease-in-out;
  -webkit-border-radius: 5px 5px 5px 5px;
  border-radius: 5px 5px 5px 5px;
}

input[type=text]:focus {
  background-color: #fff;
  border-bottom: 2px solid #5fbae9;
}

input[type=text]:placeholder {
  color: #cccccc;
}



/* ANIMATIONS */

/* Simple CSS3 Fade-in-down Animation */


@-webkit-keyframes fadeInDown {
  0% {
    opacity: 0;
    -webkit-transform: translate3d(0, -100%, 0);
    transform: translate3d(0, -100%, 0);
  }
  100% {
    opacity: 1;
    -webkit-transform: none;
    transform: none;
  }
}

@keyframes fadeInDown {
  0% {
    opacity: 0;
    -webkit-transform: translate3d(0, -100%, 0);
    transform: translate3d(0, -100%, 0);
  }
  100% {
    opacity: 1;
    -webkit-transform: none;
    transform: none;
  }
}

/* Simple CSS3 Fade-in Animation */
@-webkit-keyframes fadeIn { from { opacity:0; } to { opacity:1; } }
@-moz-keyframes fadeIn { from { opacity:0; } to { opacity:1; } }
@keyframes fadeIn { from { opacity:0; } to { opacity:1; } }

.fadeIn {
  opacity:0;
  -webkit-animation:fadeIn ease-in 1;
  -moz-animation:fadeIn ease-in 1;
  animation:fadeIn ease-in 1;

  -webkit-animation-fill-mode:forwards;
  -moz-animation-fill-mode:forwards;
  animation-fill-mode:forwards;

  -webkit-animation-duration:1s;
  -moz-animation-duration:1s;
  animation-duration:1s;
}


/* Simple CSS3 Fade-in Animation */
.underlineHover:after {
  display: block;
  left: 0;
  bottom: -10px;
  width: 0;
  height: 2px;
  background-color: #56baed;
  content: "";
  transition: width 0.2s;
}

.underlineHover:hover {
  color: #0d0d0d;
}

.underlineHover:hover:after{
  width: 100%;
}



/* OTHERS */

*:focus {
    outline: none;
} 

#icon {
  width:60%;
}

label{
  font-weight: bold;
  color: black;

}

.linkto{
  color: rgb(14, 78, 141);
  font-weight: bold;
  padding-left: 30px;
}

</style>
<%= link_to 'Back' , :back , class:"linkto"%>


<div class="d-flex align-items-center justify-content-center">
  <h1>Edit Your Profile</h1>
</div>

<div class="wrapper fadeInDown">
  <div id="formContent">

<%= form_with(model: @user,local: true) do |f| %>

  <% if @user.errors.any?  %>
    <div>
      <% @user.errors.full_messages.each do |messages| %>
        <div> <%= messages %> </div>
      <% end %>
    </div>
  <% end %>

  <div class="form-group">
  <%= f.label :name %><br/>
  <%= f.text_field :name  , placeholder: "name",required: true%>
</div>

<br/>
<div class="form-group">
  <%= f.label :email %><br/>
  <%= f.email_field :email , placeholder: "email" ,required: true%>
</div>

<br/>

<div class="form-group">
  <%= f.label :password %><br/>
  <%= f.password_field :password_digest  , placeholder: "password"%>
</div>

<br/>
<div class="form-group">
  <%= f.label :address %><br/>
  <%= f.text_area :address  , placeholder: "address", :cols => 24, :rows => 8 ,required: true%>
</div>

<br/>
<div class="form-group">
  <%= f.label :phone_number%><br/>
  <%= f.text_field :phone_number , placeholder: "phone number",required: true %>
</div>

<br/>


<br/>
<div>
<%= f.submit "Update" %>
</div>
</div>
</div>
<% end %>

app/views/users/index.html.erb
<style>
.sizeit{
  width:100%;
  height:720px
  background-size:cover;
  background-repeat:no-repeat;
  
}

.carousel-item{
  height:60rem;
  background:#777;
  position:relative;
}
.overlay-image{
  position:absolute;
  bottom:0;
  left:0;
  right:0;
  top:0;
  background-size:cover;
  background-position:center;
  
}
</style>
      

<div id="carouselExampleCaptions" class="carousel slide" data-bs-ride="carousel">
  <div class="carousel-indicators">
    <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="0" class="active" aria-current="true" aria-label="Slide 1"></button>
    <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="1" aria-label="Slide 2"></button>
    <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="2" aria-label="Slide 3"></button>
  </div>
  <div class="carousel-inner">
  <div class="sizeit">
    <div class="carousel-item active">
      <div class="overlay-image">
        <%= image_tag("h2.jpg") %>
      </div>
     
      <div class="carousel-caption d-none d-md-block">
        <h5>Welcome to Car Zone</h5>
        <p>Sell and Buy</p>
      </div>
    </div>
    <div class="carousel-item">
    <div class="overlay-image">
      <%= image_tag("img.webp") %>
     </div>
      <div class="carousel-caption d-none d-md-block">
        <h5>Exciting offers</h5>
        
      </div>
      </div>
    </div>
    <div class="carousel-item">
    <div class="overlay-image">
       <%= image_tag("img2.webp") %>
      </div>
      <div class="carousel-caption d-none d-md-block">
        <h5>New Releases</h5>
        
      </div>
    </div>
  </div>
  <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Previous</span>
  </button>
  <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Next</span>
  </button>
</div>

app/views/users/new.html.erb
<style>
.alert{
  padding:20px;
  margin-bottom:20px;
  border: 1px solid black
}

html {
  background-color: black;
}

body {
  font-family: "Poppins", sans-serif;
  height: 100vh;
}

a {
  color: #92badd;
  display:inline-block;
  text-decoration: none;
  font-weight: 400;
}

h2 {
  text-align: center;
  font-size: 16px;
  font-weight: 600;
  text-transform: uppercase;
  display:inline-block;
  margin: 40px 8px 10px 8px; 
  color: #cccccc;
}



/* STRUCTURE */

.wrapper {
  display: flex;
  align-items: center;
  flex-direction: column; 
  justify-content: center;
  width: 100%;
  min-height: 100%;
  padding: 20px;
}

#formContent {
  -webkit-border-radius: 10px 10px 10px 10px;
  border-radius: 10px 10px 10px 10px;
  background: #fff;
  padding: 30px;
  width: 90%;
  max-width: 450px;
  position: relative;
  padding: 0px;
  -webkit-box-shadow: 0 30px 60px 0 rgba(0,0,0,0.3);
  box-shadow: 0 30px 60px 0 rgba(0,0,0,0.3);
  text-align: center;
}

#formFooter {
  background-color: #f6f6f6;
  border-top: 1px solid #dce8f1;
  padding: 25px;
  text-align: center;
  -webkit-border-radius: 0 0 10px 10px;
  border-radius: 0 0 10px 10px;
}



/* TABS */

h2.inactive {
  color: #cccccc;
}

h2.active {
  color: #0d0d0d;
  border-bottom: 2px solid #5fbae9;
}



/* FORM TYPOGRAPHY*/

input[type=button], input[type=submit], input[type=reset]  {
  background-color: #56baed;
  border: none;
  color: white;
  padding: 15px 80px;
  text-align: center;
  text-decoration: none;
  display: inline-block;
  text-transform: uppercase;
  font-size: 13px;
  -webkit-box-shadow: 0 10px 30px 0 rgba(95,186,233,0.4);
  box-shadow: 0 10px 30px 0 rgba(95,186,233,0.4);
  -webkit-border-radius: 5px 5px 5px 5px;
  border-radius: 5px 5px 5px 5px;
  margin: 5px 20px 40px 20px;
  -webkit-transition: all 0.3s ease-in-out;
  -moz-transition: all 0.3s ease-in-out;
  -ms-transition: all 0.3s ease-in-out;
  -o-transition: all 0.3s ease-in-out;
  transition: all 0.3s ease-in-out;
}

input[type=button]:hover, input[type=submit]:hover, input[type=reset]:hover  {
  background-color: #39ace7;
}

input[type=button]:active, input[type=submit]:active, input[type=reset]:active  {
  -moz-transform: scale(0.95);
  -webkit-transform: scale(0.95);
  -o-transform: scale(0.95);
  -ms-transform: scale(0.95);
  transform: scale(0.95);
}

input[type=text] {
  background-color: #f6f6f6;
  border: none;
  color: #0d0d0d;
  padding: 15px 32px;
  text-align: center;
  text-decoration: none;
  display: inline-block;
  font-size: 16px;
  margin: 5px;
  width: 85%;
  border: 2px solid #f6f6f6;
  -webkit-transition: all 0.5s ease-in-out;
  -moz-transition: all 0.5s ease-in-out;
  -ms-transition: all 0.5s ease-in-out;
  -o-transition: all 0.5s ease-in-out;
  transition: all 0.5s ease-in-out;
  -webkit-border-radius: 5px 5px 5px 5px;
  border-radius: 5px 5px 5px 5px;
}
input[type=email] {
  background-color: #f6f6f6;
  border: none;
  color: #0d0d0d;
  padding: 15px 32px;
  text-align: center;
  text-decoration: none;
  display: inline-block;
  font-size: 16px;
  margin: 5px;
  width: 85%;
  border: 2px solid #f6f6f6;
  -webkit-transition: all 0.5s ease-in-out;
  -moz-transition: all 0.5s ease-in-out;
  -ms-transition: all 0.5s ease-in-out;
  -o-transition: all 0.5s ease-in-out;
  transition: all 0.5s ease-in-out;
  -webkit-border-radius: 5px 5px 5px 5px;
  border-radius: 5px 5px 5px 5px;
}
input[type=password] {
  background-color: #f6f6f6;
  border: none;
  color: #0d0d0d;
  padding: 15px 32px;
  text-align: center;
  text-decoration: none;
  display: inline-block;
  font-size: 16px;
  margin: 5px;
  width: 85%;
  border: 2px solid #f6f6f6;
  -webkit-transition: all 0.5s ease-in-out;
  -moz-transition: all 0.5s ease-in-out;
  -ms-transition: all 0.5s ease-in-out;
  -o-transition: all 0.5s ease-in-out;
  transition: all 0.5s ease-in-out;
  -webkit-border-radius: 5px 5px 5px 5px;
  border-radius: 5px 5px 5px 5px;
}

textarea {
  background-color: #f6f6f6;
  border: none;
  color: #0d0d0d;
  padding: 15px 32px;
  text-align: center;
  text-decoration: none;
  display: inline-block;
  font-size: 16px;
  margin: 5px;
  width: 85%;
  border: 2px solid #f6f6f6;
  -webkit-transition: all 0.5s ease-in-out;
  -moz-transition: all 0.5s ease-in-out;
  -ms-transition: all 0.5s ease-in-out;
  -o-transition: all 0.5s ease-in-out;
  transition: all 0.5s ease-in-out;
  -webkit-border-radius: 5px 5px 5px 5px;
  border-radius: 5px 5px 5px 5px;
}


.dd{
  text-align-last: center;
  font-size: 16px;
  margin: 5px;
  width: 85%;
  padding: 15px 32px;


}

input[type=text]:focus {
  background-color: #fff;
  border-bottom: 2px solid #5fbae9;
}

input[type=text]:placeholder {
  color: #cccccc;
}



/* ANIMATIONS */

/* Simple CSS3 Fade-in-down Animation */
.fadeInDown {
  -webkit-animation-name: fadeInDown;
  animation-name: fadeInDown;
  -webkit-animation-duration: 1s;
  animation-duration: 1s;
  -webkit-animation-fill-mode: both;
  animation-fill-mode: both;
}

@-webkit-keyframes fadeInDown {
  0% {
    opacity: 0;
    -webkit-transform: translate3d(0, -100%, 0);
    transform: translate3d(0, -100%, 0);
  }
  100% {
    opacity: 1;
    -webkit-transform: none;
    transform: none;
  }
}

@keyframes fadeInDown {
  0% {
    opacity: 0;
    -webkit-transform: translate3d(0, -100%, 0);
    transform: translate3d(0, -100%, 0);
  }
  100% {
    opacity: 1;
    -webkit-transform: none;
    transform: none;
  }
}

/* Simple CSS3 Fade-in Animation */
@-webkit-keyframes fadeIn { from { opacity:0; } to { opacity:1; } }
@-moz-keyframes fadeIn { from { opacity:0; } to { opacity:1; } }
@keyframes fadeIn { from { opacity:0; } to { opacity:1; } }

.fadeIn {
  opacity:0;
  -webkit-animation:fadeIn ease-in 1;
  -moz-animation:fadeIn ease-in 1;
  animation:fadeIn ease-in 1;

  -webkit-animation-fill-mode:forwards;
  -moz-animation-fill-mode:forwards;
  animation-fill-mode:forwards;

  -webkit-animation-duration:1s;
  -moz-animation-duration:1s;
  animation-duration:1s;
}


/* Simple CSS3 Fade-in Animation */
.underlineHover:after {
  display: block;
  left: 0;
  bottom: -10px;
  width: 0;
  height: 2px;
  background-color: #56baed;
  content: "";
  transition: width 0.2s;
}

.underlineHover:hover {
  color: #0d0d0d;
}

.underlineHover:hover:after{
  width: 100%;
}



/* OTHERS */

*:focus {
    outline: none;
} 

#icon {
  width:60%;
}

.alert{
  padding:20px;
  margin-bottom:20px;
  border: 1px solid black
}

label{
  font-weight: bold;
  color: black;

}

</style>

<div class="d-flex align-items-center justify-content-center">
  <h1>Sign Up</h1>
</div>
<%= form_with(user: @user,url: signedup_path) do |f| %>




  
  <% if @user.errors.any?  %>
    <div>
      <div class="alert alert-danger" role="alert">
        <h4 class: "alert-heading">Check for below errors.....</h4>
    
          <% @user.errors.full_messages.each do |messages| %>
            <div class: "mb-0"> <%= messages %> </div>
          <% end %>
      </div>
    </div>
  <% end %>



<div class="wrapper fadeInDown">
  <div id="formContent">

    <div >
      <%= f.label :name %><br/>
      <%= f.text_field :name , placeholder: "name",required: true%>
    </div>

    <br/>
    <div >
      <%= f.label :email %><br/>
      <%= f.email_field :email, placeholder: "email",required: true %>
    </div>

    <br/>
    <div >
      <%= f.label :password %><br/>
      <%= f.password_field :password , placeholder: "password" , required: true%>
    </div>

    <br/>
    <div >
      <%= f.label :address %><br/>
      <%= f.text_area :address , placeholder: "address"  %>
    </div>
    
    <br/>
    <div>
      <%= f.label :phone_number%><br/>
      <%= f.text_field :phone_number, placeholder: "phone number" , required: true %>
    </div>

    <br/>
    <div >
      <%= f.label :user_type %><br/>
      <div class="dd">
      
      <%= select_tag :user_type, options_for_select([['Seller', 1], ['Buyer', 2]]) , class: "form-control", :style => "width:380px"%>  
      </div>
    </div>

    <br/>
    <div>
    <%= f.submit "Sign Up"%>
    </div>
    </div>
  </div>
<% end %>