config/routes.rb
Rails.application.routes.draw do
  resources :pics
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  get 'signup', to: "users#new"
  post 'signedup', to: "users#create"
  root  to: 'users#index'


  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  get 'logout', to: 'sessions#destroy'

  get 'cars', to: 'cars#index'
  resources :users, only: [:edit, :update,:show]
  resources :cars, only: [:show, :index, :new, :create, :edit, :update]
  resources :orders, only: [:new, :create]
  
  get 'ordered', to: 'cars#display_ordered'
  get 'checkout',to: 'cars#add_to_order'

  get 'search', to: 'cars#search'
  get 'comment',to: 'cars#comment'
  patch 'add_comment',to: 'cars#add_comment'

  
  
end

app/models/car.rb
class Car < ApplicationRecord
    belongs_to :user
    has_many_attached :images
    has_one :order, dependent: :destroy
    
    validates :brand,
                presence: true

    validates :price,
                presence: true

    validates :color ,
                presence: true

    module FuelType
        PETROL = 0
        DIESEL = 1
        ETHANOL = 2
        ELECTRIC_BATTERY=3
        HYDROGEN=4

        FUEL_TYPE_NAME_MAP = {
            PETROL => "Petrol",
            DIESEL => "Diesel",
            ETHANOL => "Ethanol",
            ELECTRIC_BATTERY => "Electric Battery",
            HYDROGEN  => "Hydrogen"
        }

        def self.all
            [PETROL, DIESEL, ETHANOL, ELECTRIC_BATTERY, HYDROGEN]
        end
    end

    module CarType 
        SUV=0
        HATCHBACK=1
        CROSSOVER=2
        CONVERTIBLE=3
        SEDAN=4
        SPORTS=5
        COUPE=6
        MINIVAN=7
        WAGON=8
        PICK_UP_TRUCK=9
        def self.all
            [SUV,HATCHBACK,CROSSOVER,CONVERTIBLE,SEDAN,SPORTS,COUPE,MINIVAN,WAGON,PICK_UP_TRUCK]
        end
    end

    module Condition 
        NEW =0
        SECOND_HAND=1
        def self.all
            [NEW,SECOND_HAND]
        end
    end
    module Status
        AVAILABLE=0
        SOLD=1
        def self.all 
            [AVAILABLE,SOLD]
        end
    end
                
   def images_as_thumbnails
    images.map do |img|
        img.variant(resize_to_limit: [250,250]).processed

    end
    def images_size
        images.map do |img|
            img.size("500x500")
        end
    end
   end
   validates :brand, 
                    presence: true

end

app/controllers/cars_controller.rb
class CarsController < ApplicationController
    before_action :require_user

    def num_to_bool(x)
        if x==false
            return false
        else
            return true
        end
    end
    def index
       
        #if !params['status'].blank?
        #    params['status']=[0,1]
        #end
        
        @filter_options = {}
        
        @filter_options[:fuel_type] = [
        
           # Car::FuelType.constants.each do |type|
           #     @filter_options[:fuel_type].append(label: Car::FuelType::FUEL_TYPE_NAME_MAP[type], value: type, checked: num_to_bool(params.dig(:fuel_type,Car::FuelType.const_get(type))))
           # end

            {  label: "Petrol", value: Car::FuelType::PETROL.to_s, checked: params[:fuel_type]&.include?("0") },
            { label: "Diesel", value:Car::FuelType::DIESEL,checked: params[:fuel_type]&.include?("1") },
            { label: "Ethanol", value: Car::FuelType::ETHANOL,checked: params[:fuel_type]&.include?("2") },
            { label: "Electric Battery", value:Car::FuelType::ELECTRIC_BATTERY,checked: params[:fuel_type]&.include?("3") },
            { label: "Hydogen", value:Car::FuelType::HYDROGEN,checked: params[:fuel_type]&.include?("4")}
    ]
        

        @filter_options[:car_type]=[
            {label:"Suv",value: Car::CarType::SUV,checked: params[:car_type]&.include?("0") },
            {label:"Hatchback",value: Car::CarType::HATCHBACK,checked: params[:car_type]&.include?("1") },
            {label:"Crossover",value: Car::CarType::CROSSOVER,checked: params[:car_type]&.include?("2") },
            {label:"Convertible",value: Car::CarType::CONVERTIBLE,checked: params[:car_type]&.include?("3") },
            {label:"Sedan",value: Car::CarType::SEDAN,checked: params[:car_type]&.include?("4") },
            {label:"Sports",value: Car::CarType::SPORTS,checked: params[:car_type]&.include?("5") },
            {label:"Coupe",value: Car::CarType::COUPE,checked: params[:car_type]&.include?("6") },
            {label:"Minivan",value: Car::CarType::MINIVAN,checked: params[:car_type]&.include?("7") },
            {label:"Wagon",value: Car::CarType::WAGON,checked: params[:car_type]&.include?("8") },
            {label:"Pick Up Truck",value: Car::CarType::PICK_UP_TRUCK,checked: params[:car_type]&.include?("9") }
        ]

        @filter_options[:condition]=[
            {label:"New", value:Car::Condition::NEW,checked:params[:condition]&.include?("0")},
            {label:"Second Hand", value:Car::Condition::SECOND_HAND,checked:params[:condition]&.include?("1")}

        ]

        @filter_options[:status]=[
            {label:"Available", value:Car::Status::AVAILABLE,checked: params[:status]&.include?("0")},

            {label:"Sold", value:Car::Status::SOLD,checked:params[:status]&.include?("1")}

        ]

        
#
      #  @filter_options[:fuel_type] = Car::FuelType.all.map do |fuel_type|
      #      { label: Car::FuelType::FUEL_TYPE_NAME_MAP[fuel_type], value: fuel_type, checked: params[:fuel_type] == fuel_type}
      #  end
#
      #  @filter_options[:fuel_type].each do |fuel_type|
      #      <label>fuel_type[label</label>
      #      <input type="checkbox" value=fuel_type.value checked=fuel_type.checked>
      #  end
#
        
        
        if current_user.user_type==2
            if params['fuel_type'].blank? and params['car_type'].blank? and params['condition'].blank? and params['status'].blank?
                @cars =Car.order('status')
            elsif !params['fuel_type'].blank? and !params['car_type'].blank? and !params['condition'].blank? and !params['status'].blank?
                
                @cars=Car.where(car_type:params['car_type'],fuel_type: params['fuel_type'],condition: params['condition'],status:params['status']).order('status')
            else
                search_hash = {}
                #if params['fuel_type'].blank?
                #    fu=[0,1,2,3,4]
                #else
                #    fu=params['fuel_type']
                #end
                #if params['car_type'].blank?
                #   ca=[0,1,2,3,4,5,6,7,8,9]
                #else
                #    ca=params['car_type']
                #end
                #if params['condition'].blank?
                #    con=[0,1]
                #else
                #    con=params['condition']
                #end
                #if params['status'].blank?
                #    status=[0,1]
                #else
                #    status=params[:status]
                #end
                
                if params['fuel_type'].present?
                    search_hash[:fuel_type]=params['fuel_type']
                end
                if params['car_type'].present?
                    search_hash[:car_type]=params['car_type']
                end
                if params['condition'].present?
                    search_hash[:condition]=params['condition']
                end
                if params['status'].present?
                    search_hash[:status]=params['status']
                end

                @cars=Car.where(search_hash).order('status')

            end
            
            if params['price']=="high to low"
                @cars=@cars.order('price DESC').paginate(page: params[:page], per_page: 8)
            elsif params['price']=="low to high"
                @cars=@cars.order('price').paginate(page: params[:page], per_page: 8)
            else
                @cars=@cars.paginate(page: params[:page], per_page: 8)
            end

        else
            if params['fuel_type'].blank? and params['car_type'].blank?  and  params['condition'].blank? and params['status'].blank?       
                @cars=Car.where(user_id: current_user.id).order('status').paginate(page:params[:page],per_page:8)
            else
            
                @cars=Car.where(user_id: current_user.id,car_type:params['car_type'],fuel_type: params['fuel_type'],condition: params['condition'],status:params['status']).order('status').paginate(page:params[:page],per_page:8)
            end


        end

    end

    def show
        @car_check=Car.find(params[:id])
        if @car_check.user_id !=current_user.id && current_user.user_type==1
            flash[:alert] ="You cannot view that car"
            redirect_to cars_path

        else
        
        @car=Car.find(params[:id])
        end
        
        
    end

    def new
        if current_user.user_type==1
            @car=Car.new
        else
            flash[:alert]="You dont have permission to create"
            redirect_to cars_path
        end
    end

    def edit
        if current_user.user_type==1 
            @car=Car.find(params[:id])
            

            if @car.user_id!=current_user.id
                flash[:alert]="You dont have rights"
                redirect_to cars_path
            end
        else
            flash[:alert]="You dont have rights"
            redirect_to cars_path
        end
    end

    def create
        
        @car = Car.new(params.permit(:brand, :price, :car_type, :fuel_type, :condition, :color, :status, images: []))
        
       
        @car.brand=@car.brand.upcase
        @car.user_id= current_user.id  #check here
        
        if @car.save
            flash[:notice]="Car uploaded"
            redirect_to cars_path
        else
            render 'new', status: 302
        end
    end

    def length

    end

    def update
        
        @car = Car.find(params[:id])
        @car1=Car.new(params.require(:car).permit(:brand, :price, :car_type, :fuel_type, :condition, :color, :status, images: []))
        if @car1.images.count==0
            if @car.update(params.require(:car).permit(:brand.upcase, :price, :car_type, :fuel_type, :condition, :color, :status))
                flash[:notice]="Car updated"
                redirect_to cars_path
            else
                render 'edit', status: 302
            end
        else
            if @car.update(params.require(:car).permit(:brand, :price, :car_type, :fuel_type, :condition, :color, :status, images: []))
                flash[:notice]="Car updated"
                redirect_to cars_path
            else
                render 'edit', status: 302
            end

        end
    end
    def comment
        if current_user.user_type==2
            @order_details=Order.find_by(car_id:params[:format])
        else
            flash[:alert]="You cannot see the comment"
            redirect_to cars_path
        end
        
        


    end

    def add_comment
     
        
        @order_details=Order.find(params[:format])
        @order_details.comment=params[:order][:comment]
        @order_details.save
        flash[:alert]="comments added"
        redirect_to cars_path
    end
    
    def add_to_order
        
        @order=Order.new
        @order.user_id=current_user.id
        @order.car_id=params[:format]
        @car_data=Car.find( @order.car_id)
        @car_data.status=1
        @order.save
        @car_data.save  
        
        PostMailer.with(user:current_user,car:@car_data).post_created.deliver_now
        flash[:notice]="Car added to order"
        redirect_to cars_path
    end

    def display_ordered

        if current_user.user_type==2 
            @orders=Order.where(user_id: current_user.id).paginate(page: params[:page],per_page:1)
        else 
            @cars=Car.where(user_id: current_user.id)
            @seller_cars=@cars.where(status:1).paginate(page:params[:page],per_page:1)
        end 

    end


    #def search
   #     byebug
     #   @car1 = Car.new(params.require(:params).permit( :fuel_type))
    #    @cars=Car.where(fuel_type: @car1.fuel_type)
     #   redirect_to cars_path(@cars)
   # end
end

app/views/cars/_display_errors.html.erb
<% byebug %>
<% if error_objects.any? %>
  <h2>Following errors prevented from creating </h2>
  <ul>
  <%= "hi" %>
  <% error_objects.full_messages.each do |msg| %>
     <li> <%= msg %> </li>

  <% end %>
  </ul>
<% end %>

app/views/cars/comment.html.erb
<style>
    h1{
        text-align: center;
        color: blueviolet;
    }
    .centerit {
        display: flex;
        justify-content: center;
        align-items: center;
        height: 150px;
        
      }
      textarea {
    display: block;
    margin-left: auto;
    margin-right: auto;
}
    .comment{
        text-align: center;
        font-size: 2.5em;
    }
    .but{
        display: flex;
        justify-content: center;
        align-items: center;
        height: 200px;
        
    }
    h2{
        text-align: center;
    }

    .linkto{
  color: rgb(14, 78, 141);
  font-weight: bold;
  padding-left: 30px;
  text-decoration: none;
}

</style>

<%= link_to 'Back', :back ,class:"linkto" %>


<br/><br/><br/>
<% if @order_details.comment.blank? && current_user.id!=@order_details.user_id%>
    <h2> Buyer didn't post a comment </h2>
<% else %>

    <% if @order_details.user_id==current_user.id %>
        <%= form_with(model: @order_details,local: true,url:add_comment_path(@order_details) ) do |f| %>
            
            <div class="form-group">
            <div class="comment"> <%= f.label :comment %><br/></div>
            <br/><br/>
                <%= f.text_area :comment ,size:"50x4" %>
            </div>
           
            <div class="but">
            <%= f.submit "Add", class: "btn btn-primary" %>
            </div>
        <% end %>

    <% else %>
    <div class="comment"> Comment</div>
    <br/><br/>
        <div class="form-group">
            <textarea rows="4" cols="50"   readonly><%= @order_details.comment %></textarea>
        </div>
    <%end%>
   

<% end %>

app/views/cars/index.html.erb
<style>
h1{
    text-align:center;
    
}
.flickr_pagination {
  text-align: center;
  padding: 0.3em;
  cursor: default; }
  .flickr_pagination a, .flickr_pagination span, .flickr_pagination em {
    padding: 0.2em 0.5em; 
    border-radius: 5p
}
  .flickr_pagination .disabled {
    color: #aaaaaa; }
  .flickr_pagination .current {
    font-style: normal;
    font-weight: bold;
    color: black; }
  .flickr_pagination a {
    border: 1px solid #dddddd;
    color: #0063dc;
    text-decoration: none; }
    .flickr_pagination a:hover, .flickr_pagination a:focus {
      border-color: #003366;
      background: #0063dc;
      color: white; }
  .flickr_pagination .page_info {
    color: #aaaaaa;
    padding-top: 0.8em; }
  .flickr_pagination .previous_page, .flickr_pagination .next_page {
    border-width: 2px; }
  .flickr_pagination .previous_page {
    margin-right: 1em; }
  .flickr_pagination .next_page {
    margin-left: 1em; }



.embed-responsive .card-img-top {
    object-fit: cover;
}
.reply_toggle_button {
    width: 70px;
    cursor: pointer;
   
}
.search{
    margin-left: auto;
  margin-right: auto;
}
.a{
    text-align: center;
}

</style>

<script type="text/javascript">
   
        let toggles = button => {
            console.log("check")
     let element = document.getElementById("myselect") ;
     let hidden = element.getAttribute("hidden");
    
     if (hidden) {
        element.removeAttribute("hidden");
        button.innerText = "Hide Select";
     } else {
        element.setAttribute("hidden", "hidden");
        button.innerText = "Show Select";
     }
     
  }
  let toggle1 = button => {
            console.log("check")
     let element = document.getElementById("myselect1") ;
     let hidden = element.getAttribute("hidden");
    
     if (hidden) {
        element.removeAttribute("hidden");
        button.innerText = "Hide Select";
     } else {
        element.setAttribute("hidden", "hidden");
        button.innerText = "Show Select";
     }
     
  }

  let toggle2 = button => {
            console.log("check")
     let element = document.getElementById("myselect2") ;
     let hidden = element.getAttribute("hidden");
    
     if (hidden) {
        element.removeAttribute("hidden");
        button.innerText = "Hide Select";
     } else {
        element.setAttribute("hidden", "hidden");
        button.innerText = "Show Select";
     }
     
  }
  let toggle3 = button => {
            console.log("check")
     let element = document.getElementById("myselect3") ;
     let hidden = element.getAttribute("hidden");
    
     if (hidden) {
        element.removeAttribute("hidden");
        button.innerText = "Hide Select";
     } else {
        element.setAttribute("hidden", "hidden");
        button.innerText = "Show Select";
     }
     
  }
  let toggle4 = button => {
            console.log("check")
     let element = document.getElementById("myselect4") ;
     let hidden = element.getAttribute("hidden");
    
     if (hidden) {
        element.removeAttribute("hidden");
        button.innerText = "Hide Select";
     } else {
        element.setAttribute("hidden", "hidden");
        button.innerText = "Show Select";
     }
     
  }
    </script>

<% if logged_in? %>





<!-- CODE FOR FILTERS  -->
<% if logged_in?  && current_user.user_type==2%>

      
      
    
  <%= form_with(car: :car,method: :get, url: cars_path) do |f| %>
  <br/><br/>
  <div class="a">
    <p> <b>Filter your options </b></p>
</div>
        
        <div >
           <div >
            <table class="search">
                <tr>
                    <td  width="30%">
            <span class="reply_toggle_button float-right h6" onclick='toggles()'>
                <small class="text-primary">Search Car Type</small>
              </span>
           </div>
            
            
                    <div id="myselect" hidden="hidden">
                    
                    <%= f.label :car_type %> <br/>
                    <table>
                    <% @filter_options[:car_type].each do |car_type1| %>
                    <% if car_type1[:label]=="Convertible" || car_type1[:label]=="Coupe" || car_type1[:label]=="Pick Up Truck" %>
                        <tr>
                    <% end  %>
                        <td>
                        <%= f.check_box :car_type,{multiple:true, checked: car_type1[:checked]} , car_type1[:value], false %>

                        <%= f.label car_type1[:label] %>
                        </td>
                        <% if car_type1[:label]=="Crossover" || car_type1[:label]=="Sports" || car_type1[:label]=="Wagon" %>
                    </tr>
                    <% end  %>
                    <% end %>
                    </table>
                </div>
            
        </div>
        </td>
  
        

        <td width="30%">
       <div >
            <span class="reply_toggle_button float-right h6" onclick='toggle1()'>
                <small class="text-primary">Search  Fuel Type</small>
              </span>
        </div>
        <div id="myselect1" hidden="hidden">
            <%= f.label :fuel_type %><br/>

            <table>
            <% @filter_options[:fuel_type].each do |fuel_type1| %>
                <% if fuel_type1[:label]=="Electric Battery" %>
                    <tr>
                <% end %>
            
                <td>
                <%= f.check_box :fuel_type,{multiple:true, checked: fuel_type1[:checked]} , fuel_type1[:value], false %>

                <%= f.label fuel_type1[:label] %>
                </td>
                <% if fuel_type1[:label]=="Ethanol" %>
                    </tr>
                <% end %>
            <% end %>
        </table>
           
        </div>
    </td>



    <td width="30%">
        <div >
            <span class="reply_toggle_button float-right h6" onclick='toggle2()'>
                <small class="text-primary">Search Condition Type</small>
              </span>
           </div>
        <div id="myselect2" hidden="hidden">
            <%= f.label :condition %> <br/>
            <% @filter_options[:condition].each do |condition1| %>


            
                    <%= f.check_box :condition,{multiple:true, checked: condition1[:checked]} , condition1[:value], false %>

                    <%= f.label condition1[:label] %>
                
            <% end %>
        </div>
    </td>
</tr>
<tr>
      
        <td width="30%">
        <div >
            <span class="reply_toggle_button float-right h6" onclick='toggle3()'>
                <small class="text-primary">Search Status Type</small>
              </span>
           </div>
        <div id="myselect3" hidden="hidden">
            <%= f.label :status %> <br/>
            <% @filter_options[:status].each do |status1| %>
                <%= f.check_box :status,{multiple:true, checked: status1[:checked]} , status1[:value], false %>

                <%= f.label status1[:label] %>
            <% end %>
        </div>
    </td>


    
        <td width="30%">
        <div >
            <span class="reply_toggle_button float-right h6" onclick='toggle4()'>

                <small class="text-primary">Sort price </small>
              </span>
           </div>
        <div id="myselect4" hidden="hidden">
            <p>Sort Price By</p>
            <%= f.select :price, options_for_select(["select","high to low","low to high"]),{},{class: "form-control", :style =>"width:380px"} %>
        </div></td>
        
  
        <td>
        <div>
            <%= f.submit "Search", class: "btn btn-primary" %>
        </div>
    </td>
</tr>
</table>
  <% end %>

  
<% end %>



<!-- CODE FOR FILTERS ENDS HERE -->

<br/><br/><br/>
<div class="flickr_pagination">
    <%= will_paginate @cars, :container => false %>
</div>

<div>


<div class="container">
    <div class="row gy-3">

    <%if  @cars.blank? %>
    
        <h1> NO cars found </h1>
    <% end %>
    <% @cars.each do |car| %>

        
                <div class="col-md-3">
                    <div class="card" style="width: 18rem;">




                        <% c=1 %>
                       <div class="resol"
                        <% car.images.each do |img| %>
                            
                            <%= link_to image_tag(img, size: "286x180"), class: "card-img-top embed-responsive-item", alt:"first slide" %>

                            <% if c==1 %>
                                <% break %>
                            <% end %>
                            
                            

                           
                            <% end %>
                        </div>

                           
                        
                                    

                        <div class="card-body">
                            <h5 class="card-title"> <%= car.brand %> </h5>
                            <h5 class="card-title"> Price:<%= number_with_delimiter(car.price, :delimiter => ',') %>
                            </h5>
                            <p class="card-text"><i>
                                Car Type:
                                <%= @filter_options[:car_type][car.car_type][:label] %>
                            </i> </p>
                            <p class="card-text"><i>
                                Fuel Type: 
                                <%= @filter_options[:fuel_type][car.fuel_type][:label] %>
                            </i></p>
                            <p class="card-text"><i>
                                Condition: 
                                <%= @filter_options[:condition][car.condition][:label] %>
                            </p></i>

                            <p class="card-text"><i>
                                Color:<%=  car.color %>
                            </i></p>
                            <p class="card-text"><i>
                                
                                <% if car.status==0 %>
                                <div style= "color: green;">Status: Available</div>
                                <% else %>
                                <div style= "color: #ff0000;">Status: Sold</div>
                                <% end %>
                            </i></p>
                            <% if current_user.user_type==1 %>
                                <%=link_to 'edit',edit_car_path(car) , class:"btn btn-primary" %>
                            
                                
                            <% end %>
                            
                           
                                <%=link_to 'view', car_path(car), class:"btn btn-primary" %> 
                            <% if current_user.user_type==2 && car.status==1 %>
                            
                                <%= link_to 'comment',comment_path(car), class:"btn btn-primary" %>
                           <% end %>
                           
                    
                        </div>
                    </div>
                </div>


      

            <br/><br/><br/>

    <% end %> <br/>
            
        </div>
    </div>

</div>

<div class="flickr_pagination mb-4">
    <%= will_paginate @cars, :container => false %>
</div>

<% end %>