config/routes.rb
Rails.application.routes.draw do
  resources :pics
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  get 'signup', to: "users#new"
  post 'signedup', to: "users#create"
  root  to: 'users#index'


  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  get 'logout', to: 'sessions#destroy'

  get 'cars', to: 'cars#index'
  resources :users, only: [:edit, :update,:show]
  resources :cars, only: [:show, :index, :new, :create, :edit, :update]
  resources :orders, only: [:new, :create]
  
  get 'ordered', to: 'cars#display_ordered'
  get 'checkout',to: 'cars#add_to_order'

  get 'search', to: 'cars#search'
  get 'comment',to: 'cars#comment'
  patch 'add_comment',to: 'cars#add_comment'

  
  
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>EShop</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js" integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN" crossorigin="anonymous"></script>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>
<style>

 .leftside{
  position:absolute;
  right: 90px;
  top: 0px;
  }
  .leftside2{
  position:absolute;
  right: 0px;
  top: 0px;
  }
  .cent{
  position:absolute;
  right: 1000px;
  top: 0px;
  }
  .center{
   
    font-size: 40px;
  }
</style>
  <body>

  <nav class="navbar navbar-expand-lg navbar-light bg-dark">
  <% if logged_in? %>
    <%= link_to "Car Zone", cars_path,class: "navbar-brand",style: "color: white;" %>
  <% else %>
    <%= link_to "Car Zone", root_path,class: "navbar-brand",style: "color: white;" %>
  <% end %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
  <span class="navbar-toggler-icon"></span>
</button>
<div class="collapse navbar-collapse" id="navbarNav">
  <ul class="navbar-nav">
    
    <% if logged_in? %>
      <li class="nav-item">
        <%= link_to "Edit Profile", edit_user_path(current_user.id), class: "nav-link",style: "color: white;"  %> 
      </li>
    <% else %>
      <li class="nav-item">
        <%= link_to "Sign Up", signup_path, class: "nav-link",style: "color: white;"  %> 
      </li>
    <% end %>

    

    <% if logged_in? %>
    <div class="leftside">
      <li class="nav-item">

        <%= link_to "Ordered", ordered_path, class: "nav-link",style: "color: white;"  %> 
      </li>
      </div>
    <% else %>
      <li class="nav-item">
        <%= link_to "Login", login_path, class: "nav-link",style: "color: white;" %> 
      </li>
    <% end %>

    <% if logged_in? %>
    <% if current_user.user_type==1 %>
      <li class="nav-item">
        <%= link_to "Sell Car", new_car_path, class: "nav-link",style: "color: white;"  %> 
      </li>
      <%end%>
    <% else %>
      
    <% end %>


    <% if logged_in? %>
    <div class="leftside2">
      <li class="nav-item">
        <%= link_to "Logout", logout_path, class: "nav-link",style: "color: white;" %>
        
      </li>
      </div>
    <% end %>
    
  </ul>
</div>
</nav>



    <% flash.each do |message_type, message| %>
      <% if message_type=="alert" %>
        <div class="alert alert-danger alert-dismissible fade show" role="alert">
          <%= message %>
        </div>
      <% else %>
      <div class="alert alert-success " role="alert">
        <%= message %>
      </div>
      <% end %>

    <% end %>



    <% if logged_in? %>

  <b><div class="d-flex align-items-center justify-content-center" >
     <div class="center"> Hello <% if current_user.user_type==1 %>
                Seller
            <% else %>
                Buyer
            <% end %>
            , <%= current_user.name %></div>
            </div></b>
<% end %>




      
    <%= yield %>
  </body>
</html>